---
- name: Update apt cache (Debian).
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

# Install shadowsocks-libev from source when shadowsocks_libev_install_from_source is true.
- include: install-from-source.yml
  when: shadowsocks_libev_install_from_source == true
